import jsPDF from "jspdf";

export function exportAuditPDF(results: any, narrative: string) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(10, 10, 20);
  doc.rect(0, 0, pageW, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("LUMIS.AI — Bias Audit Report", 20, 22);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { 
    year: "numeric", month: "long", day: "numeric" 
  })}`, 20, 34);

  // SDG badge
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(pageW - 70, 12, 55, 18, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text("SDG 10 Aligned", pageW - 62, 23);

  // Reset colors
  doc.setTextColor(20, 20, 20);
  let y = 55;

  // Fairness Score
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Overall Fairness Score", 20, y);
  const score = results.summary?.bias_score || 0;
  const scoreColor: [number, number, number] = score >= 75 ? [16, 185, 129] : score >= 50 ? [251, 191, 36] : [239, 68, 68];
  doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.circle(pageW - 35, y - 5, 15, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(`${score}`, pageW - 39, y);
  doc.setTextColor(20, 20, 20);
  y += 15;

  // Compliance status
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const compliant = score >= 75;
  doc.setFillColor(compliant ? 220 : 254, compliant ? 252 : 226, compliant ? 231 : 226);
  doc.roundedRect(20, y, 80, 12, 2, 2, "F");
  doc.setTextColor(compliant ? 5 : 153, compliant ? 150 : 27, compliant ? 105 : 27);
  doc.text(compliant ? "✓ EU AI Act Compliant" : "⚠ Non-Compliant — Action Required", 24, y + 8);
  doc.setTextColor(20, 20, 20);
  y += 25;

  // Key Metrics table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Fairness Metrics", 20, y);
  y += 8;

  const metrics = [
    ["Disparate Impact Ratio", String(results.metrics?.disparate_impact?.toFixed(3) || "N/A"), (results.metrics?.disparate_impact || 0) >= 0.8 ? "PASS" : "FAIL"],
    ["Statistical Parity Difference", String(results.metrics?.statistical_parity?.toFixed(3) || "N/A"), Math.abs(results.metrics?.statistical_parity || 0) <= 0.1 ? "PASS" : "FAIL"],
    ["Equal Opportunity Difference", String(results.metrics?.equal_opportunity?.toFixed(3) || "N/A"), Math.abs(results.metrics?.equal_opportunity || 0) <= 0.1 ? "PASS" : "FAIL"],
  ];

  metrics.forEach(([label, value, status]) => {
    doc.setFillColor(248, 248, 248);
    doc.rect(20, y, pageW - 40, 12, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(label, 24, y + 8);
    doc.text(value, pageW - 80, y + 8);
    doc.setTextColor(status === "PASS" ? 5 : 200, status === "PASS" ? 150 : 30, status === "PASS" ? 105 : 30);
    doc.setFont("helvetica", "bold");
    doc.text(status, pageW - 40, y + 8);
    doc.setTextColor(20, 20, 20);
    y += 14;
  });

  y += 10;

  // Top bias features
  if (results.top_features?.length) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Top Bias-Contributing Features", 20, y);
    y += 8;
    results.top_features.slice(0, 5).forEach((f: any, i: number) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`${i + 1}. ${f.feature} — ${(f.impact * 100).toFixed(1)}% impact`, 24, y);
      y += 8;
    });
  }

  y += 10;

  // Gemini narrative
  if (narrative) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("AI Audit Narrative (Gemini)", 20, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(narrative, pageW - 40);
    doc.text(lines, 20, y);
    y += lines.length * 5 + 10;
  }

  // Footer
  doc.setFillColor(10, 10, 20);
  doc.rect(0, doc.internal.pageSize.getHeight() - 20, pageW, 20, "F");
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text("Generated by LUMIS.AI — AI Fairness Auditing Platform | SDG 10: Reduced Inequalities", 20, doc.internal.pageSize.getHeight() - 8);
  doc.text("lumis.ai", pageW - 35, doc.internal.pageSize.getHeight() - 8);

  doc.save(`LUMIS_AI_Audit_Report_${new Date().toISOString().split("T")[0]}.pdf`);
}
